name: Send Line Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send-line:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install
        run: pip install -r requirements.txt

      - name: Run job
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "🔥 START"
          echo "🔥 DATABASE_URL(env) = $DATABASE_URL"
          python -m app.scheduler.jobs.line_task_job
          echo "🔥 END"
